name: MLflow CI

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn numpy scipy

      - name: Run MLflow Project
        run: mlflow run .

      - name: Upload MLflow results
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/