name: MLflow CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: 3.11

      - name: Initialize conda
        shell: bash -l {0}
        run: |
          conda info
          conda --version

      - name: Install MLflow (base env)
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Show directory structure
        run: ls -R

      - name: Run MLflow Project (WITH CONDA)
        working-directory: MLProject
        shell: bash -l {0}
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          mlflow run .

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns/